version: "3"
services:
  database-service:
    container_name: database-service
    image: deno
    restart: always
    build:
      context: ./database-service
      dockerfile: Dockerfile
      target: base
    ports:
      - "5000:5000"

  frontend:
    container_name: frontend
    image: node:18-alpine
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: base
    ports:
      - "3000:3000"

  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres:
