version: "3"
services:
  web:
    container_name: web
    image: ghcr.io/madebyqwerty/web:latest
    restart: always
    ports:
      - "5002:5002"
    networks:
      - shift-infra

  database-service:
    container_name: database-service
    image: ghcr.io/madebyqwerty/database-service:latest
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - shift-infra

  ocr-service:
    container_name: ocr-service
    image: ghcr.io/madebyqwerty/ocr-service:latest
    restart: always
    ports:
      - 5001:5001
    networks:
      - shift-infra

  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - shift-infra

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - shift-infra

networks:
  shift-infra:
    attachable: true
    name: shift-infra

volumes:
  database_postgres:
