version: "3"
services:
  frontend:
    container_name: frontend
    image: node:18-alpine
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: base
    ports:
      - "3000:3000"

  database-service:
    container_name: database-service
    image: deno
    restart: always
    build:
      context: ./database-service
      dockerfile: Dockerfile
      target: base
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - rabbitmq

  ocr-service:
    container_name: ocr-service
    restart: always
    build:
      context: ./services/ocr
      dockerfile: Dockerfile
      target: base
    ports:
      - 5001:5001

  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - database_postgres:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  database_postgres:
