/*
Database service API

REST API for interacting with the database service.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ScanCompleteInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScanCompleteInner{}

// ScanCompleteInner struct for ScanCompleteInner
type ScanCompleteInner struct {
	// When the user has more than one hour of absence, every hour of his absence will be in this array with a user_id.
	UserId *string `json:"user_id,omitempty"`
	// Only one hour of absence, if he has another hour it will be in another item in this list.
	Absence *float32 `json:"absence,omitempty"`
	// The date of the absence.
	Date *string `json:"date,omitempty"`
}

// NewScanCompleteInner instantiates a new ScanCompleteInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScanCompleteInner() *ScanCompleteInner {
	this := ScanCompleteInner{}
	return &this
}

// NewScanCompleteInnerWithDefaults instantiates a new ScanCompleteInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScanCompleteInnerWithDefaults() *ScanCompleteInner {
	this := ScanCompleteInner{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *ScanCompleteInner) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScanCompleteInner) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *ScanCompleteInner) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *ScanCompleteInner) SetUserId(v string) {
	o.UserId = &v
}

// GetAbsence returns the Absence field value if set, zero value otherwise.
func (o *ScanCompleteInner) GetAbsence() float32 {
	if o == nil || IsNil(o.Absence) {
		var ret float32
		return ret
	}
	return *o.Absence
}

// GetAbsenceOk returns a tuple with the Absence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScanCompleteInner) GetAbsenceOk() (*float32, bool) {
	if o == nil || IsNil(o.Absence) {
		return nil, false
	}
	return o.Absence, true
}

// HasAbsence returns a boolean if a field has been set.
func (o *ScanCompleteInner) HasAbsence() bool {
	if o != nil && !IsNil(o.Absence) {
		return true
	}

	return false
}

// SetAbsence gets a reference to the given float32 and assigns it to the Absence field.
func (o *ScanCompleteInner) SetAbsence(v float32) {
	o.Absence = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *ScanCompleteInner) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScanCompleteInner) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *ScanCompleteInner) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *ScanCompleteInner) SetDate(v string) {
	o.Date = &v
}

func (o ScanCompleteInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScanCompleteInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.Absence) {
		toSerialize["absence"] = o.Absence
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	return toSerialize, nil
}

type NullableScanCompleteInner struct {
	value *ScanCompleteInner
	isSet bool
}

func (v NullableScanCompleteInner) Get() *ScanCompleteInner {
	return v.value
}

func (v *NullableScanCompleteInner) Set(val *ScanCompleteInner) {
	v.value = val
	v.isSet = true
}

func (v NullableScanCompleteInner) IsSet() bool {
	return v.isSet
}

func (v *NullableScanCompleteInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScanCompleteInner(val *ScanCompleteInner) *NullableScanCompleteInner {
	return &NullableScanCompleteInner{value: val, isSet: true}
}

func (v NullableScanCompleteInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScanCompleteInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


