/*
Database service API

REST API for interacting with the database service.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"os"
)

// checks if the Scan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Scan{}

// Scan struct for Scan
type Scan struct {
	// The image of the absence table. (max 20mb)
	Img *os.File `json:"img"`
	// The week number of the absence table.
	WeekNumber int32 `json:"week_number"`
}

// NewScan instantiates a new Scan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScan(img *os.File, weekNumber int32) *Scan {
	this := Scan{}
	this.Img = img
	this.WeekNumber = weekNumber
	return &this
}

// NewScanWithDefaults instantiates a new Scan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScanWithDefaults() *Scan {
	this := Scan{}
	return &this
}

// GetImg returns the Img field value
func (o *Scan) GetImg() *os.File {
	if o == nil {
		var ret *os.File
		return ret
	}

	return o.Img
}

// GetImgOk returns a tuple with the Img field value
// and a boolean to check if the value has been set.
func (o *Scan) GetImgOk() (**os.File, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Img, true
}

// SetImg sets field value
func (o *Scan) SetImg(v *os.File) {
	o.Img = v
}

// GetWeekNumber returns the WeekNumber field value
func (o *Scan) GetWeekNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WeekNumber
}

// GetWeekNumberOk returns a tuple with the WeekNumber field value
// and a boolean to check if the value has been set.
func (o *Scan) GetWeekNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WeekNumber, true
}

// SetWeekNumber sets field value
func (o *Scan) SetWeekNumber(v int32) {
	o.WeekNumber = v
}

func (o Scan) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Scan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["img"] = o.Img
	toSerialize["week_number"] = o.WeekNumber
	return toSerialize, nil
}

type NullableScan struct {
	value *Scan
	isSet bool
}

func (v NullableScan) Get() *Scan {
	return v.value
}

func (v *NullableScan) Set(val *Scan) {
	v.value = val
	v.isSet = true
}

func (v NullableScan) IsSet() bool {
	return v.isSet
}

func (v *NullableScan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScan(val *Scan) *NullableScan {
	return &NullableScan{value: val, isSet: true}
}

func (v NullableScan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


