/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Absence
 */
export interface Absence {
    /**
     * The user's name
     * @type {string}
     * @memberof Absence
     */
    name: string;
    /**
     * The user's id
     * @type {string}
     * @memberof Absence
     */
    userId: string;
    /**
     * The absence's id.
     * @type {string}
     * @memberof Absence
     */
    id: string;
    /**
     * The lesson number
     * @type {number}
     * @memberof Absence
     */
    lesson: number;
    /**
     * Date of the absence
     * @type {string}
     * @memberof Absence
     */
    date: string;
}

/**
 * Check if a given object implements the Absence interface.
 */
export function instanceOfAbsence(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "lesson" in value;
    isInstance = isInstance && "date" in value;

    return isInstance;
}

export function AbsenceFromJSON(json: any): Absence {
    return AbsenceFromJSONTyped(json, false);
}

export function AbsenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Absence {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'userId': json['userId'],
        'id': json['id'],
        'lesson': json['lesson'],
        'date': json['date'],
    };
}

export function AbsenceToJSON(value?: Absence | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'userId': value.userId,
        'id': value.id,
        'lesson': value.lesson,
        'date': value.date,
    };
}

