/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbsencesUserIdPostRequest
 */
export interface AbsencesUserIdPostRequest {
    /**
     * 
     * @type {number}
     * @memberof AbsencesUserIdPostRequest
     */
    lesson?: number;
    /**
     * 
     * @type {string}
     * @memberof AbsencesUserIdPostRequest
     */
    date?: string;
}

/**
 * Check if a given object implements the AbsencesUserIdPostRequest interface.
 */
export function instanceOfAbsencesUserIdPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AbsencesUserIdPostRequestFromJSON(json: any): AbsencesUserIdPostRequest {
    return AbsencesUserIdPostRequestFromJSONTyped(json, false);
}

export function AbsencesUserIdPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbsencesUserIdPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lesson': !exists(json, 'lesson') ? undefined : json['lesson'],
        'date': !exists(json, 'date') ? undefined : json['date'],
    };
}

export function AbsencesUserIdPostRequestToJSON(value?: AbsencesUserIdPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lesson': value.lesson,
        'date': value.date,
    };
}

