/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AbsencesUserIdGetDefaultResponseErrors } from './AbsencesUserIdGetDefaultResponseErrors';
import {
    AbsencesUserIdGetDefaultResponseErrorsFromJSON,
    AbsencesUserIdGetDefaultResponseErrorsFromJSONTyped,
    AbsencesUserIdGetDefaultResponseErrorsToJSON,
} from './AbsencesUserIdGetDefaultResponseErrors';

/**
 * 
 * @export
 * @interface AbsencesUserIdGetDefaultResponse
 */
export interface AbsencesUserIdGetDefaultResponse {
    /**
     * 
     * @type {AbsencesUserIdGetDefaultResponseErrors}
     * @memberof AbsencesUserIdGetDefaultResponse
     */
    errors?: AbsencesUserIdGetDefaultResponseErrors;
}

/**
 * Check if a given object implements the AbsencesUserIdGetDefaultResponse interface.
 */
export function instanceOfAbsencesUserIdGetDefaultResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AbsencesUserIdGetDefaultResponseFromJSON(json: any): AbsencesUserIdGetDefaultResponse {
    return AbsencesUserIdGetDefaultResponseFromJSONTyped(json, false);
}

export function AbsencesUserIdGetDefaultResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbsencesUserIdGetDefaultResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': !exists(json, 'errors') ? undefined : AbsencesUserIdGetDefaultResponseErrorsFromJSON(json['errors']),
    };
}

export function AbsencesUserIdGetDefaultResponseToJSON(value?: AbsencesUserIdGetDefaultResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': AbsencesUserIdGetDefaultResponseErrorsToJSON(value.errors),
    };
}

