/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbsencesUserIdGet400Response
 */
export interface AbsencesUserIdGet400Response {
    /**
     * 
     * @type {string}
     * @memberof AbsencesUserIdGet400Response
     */
    id?: AbsencesUserIdGet400ResponseIdEnum;
}


/**
 * @export
 */
export const AbsencesUserIdGet400ResponseIdEnum = {
    Required: 'required',
    NotValid: 'not-valid'
} as const;
export type AbsencesUserIdGet400ResponseIdEnum = typeof AbsencesUserIdGet400ResponseIdEnum[keyof typeof AbsencesUserIdGet400ResponseIdEnum];


/**
 * Check if a given object implements the AbsencesUserIdGet400Response interface.
 */
export function instanceOfAbsencesUserIdGet400Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AbsencesUserIdGet400ResponseFromJSON(json: any): AbsencesUserIdGet400Response {
    return AbsencesUserIdGet400ResponseFromJSONTyped(json, false);
}

export function AbsencesUserIdGet400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbsencesUserIdGet400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function AbsencesUserIdGet400ResponseToJSON(value?: AbsencesUserIdGet400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

