/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AbsencesUserIdGet400ResponseErrors
 */
export interface AbsencesUserIdGet400ResponseErrors {
    /**
     * 
     * @type {Array<string>}
     * @memberof AbsencesUserIdGet400ResponseErrors
     */
    example?: Array<string>;
}

/**
 * Check if a given object implements the AbsencesUserIdGet400ResponseErrors interface.
 */
export function instanceOfAbsencesUserIdGet400ResponseErrors(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AbsencesUserIdGet400ResponseErrorsFromJSON(json: any): AbsencesUserIdGet400ResponseErrors {
    return AbsencesUserIdGet400ResponseErrorsFromJSONTyped(json, false);
}

export function AbsencesUserIdGet400ResponseErrorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbsencesUserIdGet400ResponseErrors {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'example': !exists(json, 'example') ? undefined : json['example'],
    };
}

export function AbsencesUserIdGet400ResponseErrorsToJSON(value?: AbsencesUserIdGet400ResponseErrors | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'example': value.example,
    };
}

