/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Absences
 */
export interface Absences {
    /**
     * When the user has more than one hour of absence, every hour of his absence will be in this array with a user_id.
     * @type {string}
     * @memberof Absences
     */
    id?: string;
    /**
     * The name of the user.
     * @type {string}
     * @memberof Absences
     */
    name?: string;
    /**
     * Only one hour of absence, if he has another hour it will be in another item in this list.
     * @type {number}
     * @memberof Absences
     */
    absence?: number;
    /**
     * The date of the absence.
     * @type {Date}
     * @memberof Absences
     */
    date?: Date;
}

/**
 * Check if a given object implements the Absences interface.
 */
export function instanceOfAbsences(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AbsencesFromJSON(json: any): Absences {
    return AbsencesFromJSONTyped(json, false);
}

export function AbsencesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Absences {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'absence': !exists(json, 'absence') ? undefined : json['absence'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
    };
}

export function AbsencesToJSON(value?: Absences | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'absence': value.absence,
        'date': value.date === undefined ? undefined : (value.date.toISOString().substring(0,10)),
    };
}

