/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAbsencesUserIdPost200Response
 */
export interface ApiAbsencesUserIdPost200Response {
    /**
     * The absence id.
     * @type {string}
     * @memberof ApiAbsencesUserIdPost200Response
     */
    id?: string;
    /**
     * The lesson number
     * @type {number}
     * @memberof ApiAbsencesUserIdPost200Response
     */
    lesson?: number;
    /**
     * Date of the absence
     * @type {string}
     * @memberof ApiAbsencesUserIdPost200Response
     */
    date?: string;
}

/**
 * Check if a given object implements the ApiAbsencesUserIdPost200Response interface.
 */
export function instanceOfApiAbsencesUserIdPost200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiAbsencesUserIdPost200ResponseFromJSON(json: any): ApiAbsencesUserIdPost200Response {
    return ApiAbsencesUserIdPost200ResponseFromJSONTyped(json, false);
}

export function ApiAbsencesUserIdPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAbsencesUserIdPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'lesson': !exists(json, 'lesson') ? undefined : json['lesson'],
        'date': !exists(json, 'date') ? undefined : json['date'],
    };
}

export function ApiAbsencesUserIdPost200ResponseToJSON(value?: ApiAbsencesUserIdPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'lesson': value.lesson,
        'date': value.date,
    };
}

