/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAbsencesUserIdPostRequest
 */
export interface ApiAbsencesUserIdPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiAbsencesUserIdPostRequest
     */
    lesson?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiAbsencesUserIdPostRequest
     */
    date?: string;
}

/**
 * Check if a given object implements the ApiAbsencesUserIdPostRequest interface.
 */
export function instanceOfApiAbsencesUserIdPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiAbsencesUserIdPostRequestFromJSON(json: any): ApiAbsencesUserIdPostRequest {
    return ApiAbsencesUserIdPostRequestFromJSONTyped(json, false);
}

export function ApiAbsencesUserIdPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAbsencesUserIdPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lesson': !exists(json, 'lesson') ? undefined : json['lesson'],
        'date': !exists(json, 'date') ? undefined : json['date'],
    };
}

export function ApiAbsencesUserIdPostRequestToJSON(value?: ApiAbsencesUserIdPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lesson': value.lesson,
        'date': value.date,
    };
}

