/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiUsersPostRequest
 */
export interface ApiUsersPostRequest {
    /**
     * The user's name.
     * @type {string}
     * @memberof ApiUsersPostRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the ApiUsersPostRequest interface.
 */
export function instanceOfApiUsersPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiUsersPostRequestFromJSON(json: any): ApiUsersPostRequest {
    return ApiUsersPostRequestFromJSONTyped(json, false);
}

export function ApiUsersPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiUsersPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function ApiUsersPostRequestToJSON(value?: ApiUsersPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

