/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScanPost200Response
 */
export interface ScanPost200Response {
    /**
     * The id of the scan
     * @type {string}
     * @memberof ScanPost200Response
     */
    scanId?: string;
}

/**
 * Check if a given object implements the ScanPost200Response interface.
 */
export function instanceOfScanPost200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScanPost200ResponseFromJSON(json: any): ScanPost200Response {
    return ScanPost200ResponseFromJSONTyped(json, false);
}

export function ScanPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scanId': !exists(json, 'scan_id') ? undefined : json['scan_id'],
    };
}

export function ScanPost200ResponseToJSON(value?: ScanPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'scan_id': value.scanId,
    };
}

