/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Absences } from './Absences';
import {
    AbsencesFromJSON,
    AbsencesFromJSONTyped,
    AbsencesToJSON,
} from './Absences';

/**
 * 
 * @export
 * @interface ScanCompleteScanIdPostRequest
 */
export interface ScanCompleteScanIdPostRequest {
    /**
     * 
     * @type {Absences}
     * @memberof ScanCompleteScanIdPostRequest
     */
    absences?: Absences;
}

/**
 * Check if a given object implements the ScanCompleteScanIdPostRequest interface.
 */
export function instanceOfScanCompleteScanIdPostRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScanCompleteScanIdPostRequestFromJSON(json: any): ScanCompleteScanIdPostRequest {
    return ScanCompleteScanIdPostRequestFromJSONTyped(json, false);
}

export function ScanCompleteScanIdPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanCompleteScanIdPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'absences': !exists(json, 'absences') ? undefined : AbsencesFromJSON(json['absences']),
    };
}

export function ScanCompleteScanIdPostRequestToJSON(value?: ScanCompleteScanIdPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'absences': AbsencesToJSON(value.absences),
    };
}

