/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Scan
 */
export interface Scan {
    /**
     * The image of the absence table. (max 20mb)
     * @type {Blob}
     * @memberof Scan
     */
    img: Blob;
    /**
     * The week number of the absence table.
     * @type {number}
     * @memberof Scan
     */
    weekNumber: number;
}

/**
 * Check if a given object implements the Scan interface.
 */
export function instanceOfScan(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "img" in value;
    isInstance = isInstance && "weekNumber" in value;

    return isInstance;
}

export function ScanFromJSON(json: any): Scan {
    return ScanFromJSONTyped(json, false);
}

export function ScanFromJSONTyped(json: any, ignoreDiscriminator: boolean): Scan {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'img': json['img'],
        'weekNumber': json['week_number'],
    };
}

export function ScanToJSON(value?: Scan | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'img': value.img,
        'week_number': value.weekNumber,
    };
}

