/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ScanCompleteAbsencesInner } from './ScanCompleteAbsencesInner';
import {
    ScanCompleteAbsencesInnerFromJSON,
    ScanCompleteAbsencesInnerFromJSONTyped,
    ScanCompleteAbsencesInnerToJSON,
} from './ScanCompleteAbsencesInner';

/**
 * 
 * @export
 * @interface ScanComplete
 */
export interface ScanComplete {
    /**
     * 
     * @type {Array<ScanCompleteAbsencesInner>}
     * @memberof ScanComplete
     */
    absences?: Array<ScanCompleteAbsencesInner>;
}

/**
 * Check if a given object implements the ScanComplete interface.
 */
export function instanceOfScanComplete(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScanCompleteFromJSON(json: any): ScanComplete {
    return ScanCompleteFromJSONTyped(json, false);
}

export function ScanCompleteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanComplete {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'absences': !exists(json, 'absences') ? undefined : ((json['absences'] as Array<any>).map(ScanCompleteAbsencesInnerFromJSON)),
    };
}

export function ScanCompleteToJSON(value?: ScanComplete | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'absences': value.absences === undefined ? undefined : ((value.absences as Array<any>).map(ScanCompleteAbsencesInnerToJSON)),
    };
}

