/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersGet400Response
 */
export interface UsersGet400Response {
    /**
     * 
     * @type {string}
     * @memberof UsersGet400Response
     */
    name?: UsersGet400ResponseNameEnum;
}


/**
 * @export
 */
export const UsersGet400ResponseNameEnum = {
    Required: 'required'
} as const;
export type UsersGet400ResponseNameEnum = typeof UsersGet400ResponseNameEnum[keyof typeof UsersGet400ResponseNameEnum];


/**
 * Check if a given object implements the UsersGet400Response interface.
 */
export function instanceOfUsersGet400Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersGet400ResponseFromJSON(json: any): UsersGet400Response {
    return UsersGet400ResponseFromJSONTyped(json, false);
}

export function UsersGet400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersGet400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function UsersGet400ResponseToJSON(value?: UsersGet400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

