/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersIdGet404Response
 */
export interface UsersIdGet404Response {
    /**
     * 
     * @type {string}
     * @memberof UsersIdGet404Response
     */
    user?: UsersIdGet404ResponseUserEnum;
}


/**
 * @export
 */
export const UsersIdGet404ResponseUserEnum = {
    NotFound: 'not-found'
} as const;
export type UsersIdGet404ResponseUserEnum = typeof UsersIdGet404ResponseUserEnum[keyof typeof UsersIdGet404ResponseUserEnum];


/**
 * Check if a given object implements the UsersIdGet404Response interface.
 */
export function instanceOfUsersIdGet404Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersIdGet404ResponseFromJSON(json: any): UsersIdGet404Response {
    return UsersIdGet404ResponseFromJSONTyped(json, false);
}

export function UsersIdGet404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersIdGet404Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function UsersIdGet404ResponseToJSON(value?: UsersIdGet404Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': value.user,
    };
}

