/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UsersPost400ResponseFieldErrors } from './UsersPost400ResponseFieldErrors';
import {
    UsersPost400ResponseFieldErrorsFromJSON,
    UsersPost400ResponseFieldErrorsFromJSONTyped,
    UsersPost400ResponseFieldErrorsToJSON,
} from './UsersPost400ResponseFieldErrors';

/**
 * 
 * @export
 * @interface UsersPost400Response
 */
export interface UsersPost400Response {
    /**
     * 
     * @type {UsersPost400ResponseFieldErrors}
     * @memberof UsersPost400Response
     */
    fieldErrors?: UsersPost400ResponseFieldErrors;
}

/**
 * Check if a given object implements the UsersPost400Response interface.
 */
export function instanceOfUsersPost400Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersPost400ResponseFromJSON(json: any): UsersPost400Response {
    return UsersPost400ResponseFromJSONTyped(json, false);
}

export function UsersPost400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersPost400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fieldErrors': !exists(json, 'fieldErrors') ? undefined : UsersPost400ResponseFieldErrorsFromJSON(json['fieldErrors']),
    };
}

export function UsersPost400ResponseToJSON(value?: UsersPost400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fieldErrors': UsersPost400ResponseFieldErrorsToJSON(value.fieldErrors),
    };
}

