/* tslint:disable */
/* eslint-disable */
/**
 * Database service API
 * REST API for interacting with the database service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersIdGet400Response
 */
export interface UsersIdGet400Response {
    /**
     * 
     * @type {string}
     * @memberof UsersIdGet400Response
     */
    id?: UsersIdGet400ResponseIdEnum;
}


/**
 * @export
 */
export const UsersIdGet400ResponseIdEnum = {
    NotValid: 'not-valid'
} as const;
export type UsersIdGet400ResponseIdEnum = typeof UsersIdGet400ResponseIdEnum[keyof typeof UsersIdGet400ResponseIdEnum];


/**
 * Check if a given object implements the UsersIdGet400Response interface.
 */
export function instanceOfUsersIdGet400Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UsersIdGet400ResponseFromJSON(json: any): UsersIdGet400Response {
    return UsersIdGet400ResponseFromJSONTyped(json, false);
}

export function UsersIdGet400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersIdGet400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function UsersIdGet400ResponseToJSON(value?: UsersIdGet400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

