openapi: 3.0.0
info:
  title: Shift API
  version: 0.0.2
  description: REST API for interfacing with the Shift backend
  license:
    name: Proprietary
  contact:
    name: Tomáš Kebrle
servers:
  - url: http://localhost:5000/api
  - url: https://api.qwerty.mesh.sk/api

tags:
  - name: Absences
    description: Endpoints for managing absences of users.
  - name: Users
    description: Endpoints for managing users.

paths:
  /absences/{userId}:
    $ref: "./paths/absences.yml"

  /users:
    $ref: "./paths/users.yml"

  /users/{userId}:
    $ref: "./paths/users_id.yml"

components:
  schemas:
    Absence:
      $ref: "./schemas/Absence.yml"
    User:
      $ref: "./schemas/User.yml"
    Error:
      $ref: "./schemas/Error.yml"

  parameters:
    userId:
      $ref: "./parameters/userId.yml"
