openapi: "3.0.3"
info:
  title: Database service API
  version: 0.0.1
  description: REST API for interacting with the database service.
  license:
    name: Proprietary
  contact:
    name: Tomáš Kebrle
servers:
  - url: http://localhost:5003/

paths:
  /api/users:
    $ref: "./paths/users.yml"

  /api/users/{userId}:
    $ref: "./paths/users_id.yml"

  /api/absences/{userId}:
    $ref: "./paths/absences.yml"

  /scan:
    $ref: "./paths/scan.yml"

  /ws/scan/{userId}:
    $ref: "./paths/ws_scan.yml"

  /scan/complete:
    $ref: "./paths/scan_complete.yml"

components:
  schemas:
    Absence:
      $ref: "./schemas/Absence.yml"
    User:
      $ref: "./schemas/User.yml"
    Error:
      $ref: "./schemas/Error.yml"
