name: Build and Publish Docker Images

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Database service Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./services/database/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/database-service:${{ github.sha }}

      - name: Build OCR service Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./services/ocr/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/database-service:${{ github.sha }}

      - name: Build web Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/database-service:${{ github.sha }}
