name: Generate OpenAPI client

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install OpenAPI CLI
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Moon
        run: npm install -g @moonrepo/cli

      - name: Generate client
        run: moon run gateway:generate

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update generated client [skip ci]"
