name: Generate OpenAPI client

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install OpenAPI CLI
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Moon
        run: npm install -g @moonrepo/cli

      - name: Generate client
        run: moon run database:generate

      - name: Commit generated client
        run: |
          git config --global user.email "dev@tomaskebrle.cz"
          git config --global user.name "Tomáš Kebrle"
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit --quiet -m "Generate OpenAPI client"
            git push origin HEAD:${{ github.head_ref }}
          fi
