name: Generate OpenAPI client

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenAPI CLI
        run: npm install @openapitools/openapi-generator-cli -g

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Moon
        run: npm install -g @moonrepo/cli

      - name: Generate client
        run: moon run database:generate

      - name: Commit generated client
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Generate OpenAPI client"
          git push
